### ISSUE TITLE
frontend.c needs some tweaks to be built with MSVC

### ISSUE THREAD

**Issue by nu774** [njh/twolame#12]
Hi, thanks for your works.

At line 740 of frontend.c, "int bytes_out" is declared at the middle of the block scope around it, therefore can't be compiled with compilers which doesn't support C99 (at least MSVC).
I also tried forcing C++ compilation, but C++ compilation also requires some fix, because of lines like this:
    char *string = malloc(MAX_NAME_SIZE);
(This is legal in C, but not in C++: it requires explicit cast)

**Comment by njh** [comment]
The above patch link doesn't work anymore, closing this.

If anyone has some improvements for Windows, please raise a PR.
