### ISSUE TITLE
vbr mode

### ISSUE THREAD

**Issue by richardpl** [njh/twolame#17]
It appears only mono files with vbr can be played correctly.

Is this twolame issue or there is simply no decoder which can play such files?

**Comment by eblanca** [comment]
Pull request #34 patches this vbr encoding.
I think it should work but feel free to report your own results.

**Comment by njh** [comment]
I have just merged #34 

@richardpl do you want to test to see if it works?

**Comment by richardpl** [comment]
Will take look later.

**Comment by njh** [comment]
Closing this ticket. If there are problems with the fix, please open a new issue.
