### ISSUE TITLE
About layer II

### ISSUE THREAD

**Issue by eblanca** [njh/twolame#27]
I have two questions about layer II frame format.

1. it seems the bit allocation stuff begins right after the header (eventually after the crc16) and the remaining room in frame is dedicated to the samples, so is it right to say any layer II stream may be safely cut at frame boundaries ?

2. in a frame, is there an easy way to skip the samples and jump to the ancillary bytes (if any) ? In layer III the side information block offers (among other stuff) the so-called backpointer and the length of part2+part3, so it's easy to do this. What about layer II ? is there a similar information available ?

Thank you.

**Comment by njh** [comment]
1. Yes. MPEG Layer 2 can safely be cut on frame boundaries. There frame are independent. This is one of the main reasons that people still use MPEG Layer 2. In DVB you can minimise the glitch if a frame is lost.
2. I have not done any work on twolame for quite a long time, so I can't remember exactly. 

This might be a clue for you:
https://github.com/njh/twolame/blob/master/libtwolame/energy.c#L104

The code that writes energy levels into the ancillary bytes just works backwards from the end of the frame. Or equally, I guess if you know the frame length, you could calculate it from the start.

Note that you have to use twolame_set_num_ancillary_bits() to reserve some space at the end of the frame.

**Comment by eblanca** [comment]
Thank you, I didn't know about energy levels and they may be a valuable hint.
What I actually meant is my attempt, as a reader, to locate the very end of samples in an opaque byte buffer (the raw frame) with an unknown amount of ancillary bytes set by the encoder.
Now, I see the energy levels are 3 or 5 bytes with a zero into the last-but-third position, and so it's a kind of a pattern useful for a search algorithm (I really would like a way to reach this very end without reading the entire sample block, this would require more time).

[BTW, why does the code uses the formula
`lobyte=MaxValue - 256*hibyte`
instead of
`lobyte=MaxValue%256`
which is faster and readable as well ? ]

**Comment by njh** [comment]
I am not sure how you are supposed to know the number of ancillary bits as a reader, sorry.

You could try asking on the twolame mailing list, where there are lots of other MP2 users:
https://sourceforge.net/p/twolame/mailman/twolame-discuss/

I don't know why that formula is used - most of the code came from the toolame codebase.
There are lots of things that could be improved upon.
