### ISSUE TITLE
A couple of padding policies

### ISSUE THREAD

**Issue by eblanca** [njh/twolame#43]
I see two different policies are applied when doing padding.

When I'm encoding 44.1 kHz or 22.05 kHz content and padding is selected, some frames are padded with a slot, so the bitrate results exact. This means somewhere an algorithm is evaluated in order to decide whether the current frame deserves to be padded or not.

But when I'm encoding 16/24/32/48 kHz content and padding is selected (I know there's no need in those cases), no algorithm is evaluated, so any frames are padded.

Those policies are different, and since the encoding frontend help says "--padding   force padding bit/frame on", then this means the second behaviour is meant to be right. Actually, truth be told, I expected the former to be applied.

I see a contradiction in all this, do you?

**Comment by eblanca** [comment]
The padding policy applied int 44.1/22.05 kHz encodings is into https://github.com/njh/twolame/blob/master/libtwolame/availbits.c#L58 , while the one for 32/48 kHz encondings is into https://github.com/njh/twolame/blob/master/libtwolame/twolame.c#L614

**Comment by eblanca** [comment]
More details:

- into https://github.com/njh/twolame/blob/master/libtwolame/availbits.c#L58 an algorithm is evaluated for any frames, resulting into a flag signaling either pad enabled or pad disabled. Furthermore, since this padding is taken into account when calculating the available bits, this results into more bits available into padded frames. This mismatches with original "padding slot" meaning, which was meant as an empty slot used only for matching a given bitrate.

- into https://github.com/njh/twolame/blob/master/libtwolame/twolame.c#L614 a real empty slot is put into frame, although this is wrongly placed (only for 32/48 kHz encodings).

**Comment by eblanca** [comment]
I created a pull request #48 about this issue.

**Comment by njh** [comment]
Sorry for not commenting on this previously.

I don't know very much about the padding operations  - but it looks like you have investigated it pretty well - thanks!

**Comment by njh** [comment]
Think this is resolved now with #48
