### ISSUE TITLE
Aligning frames to byte boundaries, why?

### ISSUE THREAD

**Issue by eblanca** [njh/twolame#44]
I see in https://github.com/njh/twolame/blob/master/libtwolame/twolame.c#L620 a simple check for building frames only with whole slots, that is, extact multiple of bytes.
Taken into account a frame may be fullfilled with ancillary bits, why is this constraint there?
Is this a mpeg standard/stream requirement?

**Comment by njh** [comment]
I am not sure where is is specified, but I'm fairly sure the start of frames have to be aligned to a byte boundary. This makes it much easier to synchronise the stream and find the start of a frame.

**Comment by eblanca** [comment]
Well ok, having start of frames on byte boundaries is easier indeed.
But when finalizing a frame, the routine `encode_frame` adds some ancillary bits, then checks how many bits have been written (in statement L620) to ensure they are multiple of eight (and then it complains on failure), instead it should be simpler to add ancillary bits until a multiple of eight has been reached (this should be a always-win strategy, imho).
Why this? Maybe I am missing some subtle issue...?

**Comment by njh** [comment]
Sorry, I am not sure about the details of how ancillary bits are allocated.

**Comment by eblanca** [comment]
Finally, this is not an issue with the code, I just wanted to know more about the algorithm.
So, the milestone is not due.
And the issue may be closed.
