### ISSUE TITLE
Obsolete keyword

### ISSUE THREAD

**Issue by eblanca** [njh/twolame#63]
I see the code still uses some "register" keyword for a bunch of variables.
This used to be added as a suggestion to the compiler, which would use a cpu register instead of a memory location and get a faster access to a given variable, but nowadays this choice is better done by modern compilers, AFAIK.
What do you think about removing them all ?

**Comment by njh** [comment]
Are you seeing warnings in your compiler?
Is there any harm in leaving them there?

My only concern is if people using older compilers still need it.

**Comment by eblanca** [comment]
Well, I currently have no issues here about this keyword, so in case of people still using old compilers (I didn't think of those users) it may well stay there.
