### ISSUE TITLE
Update NEWS to include summary of changes in 0.4.0 release

### ISSUE THREAD

**Issue by njh** [njh/twolame#76]

**Comment by eblanca** [comment]
Looking at the commit history and the files released on sourceforge, it seems 0.3.13 was released on 2011/1/21, despite in NEWS.md the date is 2010. Is this a typo ?

**Comment by njh** [comment]
Yeah, I think it was a typo. Corrected in 8af11d1bf1b6b30ae05df9311f4339e98691458b

**Comment by njh** [comment]
News updated (hopefully for a final time) in c7473b8e4959af779b43c0715604a4adb705df4e
