### ISSUE TITLE
Test that CRC calculation is working properly

### ISSUE THREAD

**Issue by njh** [njh/twolame#8]

**Comment by eblanca** [comment]
In my extensive test for #34 (and also for mp3guessenc validation) I encoded both mono and stereo sources, with and without padding, both mpeg1 and mpeg2 lsf, and always madplay reported successful crc verification.
So, I have no evidence of failures in this computation. Rather, I can say this works flawlessly.
I think this issue may be closed.

**Comment by njh** [comment]
Thank you very much for verifying this.

Would be good to have some automated tests to verify things like this.

But will close for now.
