### ISSUE TITLE
LT_INIT usage

### ISSUE THREAD

**Issue by vtorri** [njh/twolame#82]
Hello

in configure.ac, there are 2 LT_INIT (lines 53 and 59)
in addition, to allow the compilation of twolame, you should use LT_INIT like that : 

LT_INIT([win32-dll)

if you want, i can provide a pull request (just tell me which LT_INIT you want to suppress)

**Comment by njh** [comment]
Thanks for reporting
* Deleted one in: b43d721ff5fe45ca683b8e06fcac5f37067945e3
* Add `win32-dll` in: 3e1720f4718b84c9744c0be936192ef74f2ad573
