### ISSUE TITLE
windows compilation: -no-undefined must be added to LDFLAGS for the creation of the shared library

### ISSUE THREAD

**Issue by vtorri** [njh/twolame#83]
in libtwolame/Makefile.am, line 6, append -no-undefined to _LDFLAGS so that shared library is created, otherwise only static lib is created

thank you

**Comment by njh** [comment]
Sorry, I don't have any knowledge or experience of Windows and would not be able to test.

Would be happy to accept a Pull Request and verify that nothing else breaks.

**Comment by vtorri** [comment]
done

**Comment by vtorri** [comment]
any news for this pull request ?

**Comment by vtorri** [comment]
up :-)

**Comment by vtorri** [comment]
PR #84 merged, closing
