### ISSUE TITLE
no rule to make twolame.1

### ISSUE THREAD

**Issue by vtorri** [njh/twolame#86]
**make[2]: ***  Aucune règle pour fabriquer la cible « twolame.1 », nécessaire pour « all-am ». Arrêt.**

means "no rule to make twolame.1"

**Comment by njh** [comment]
No response, closing issue.

**Comment by vtorri** [comment]
sorry, yes, it was from git

**Comment by tfleschenberg** [comment]
Is there a reason that the bug fixed in #54 has been reintroduced? I guess many people just want to get libtwolame for their ffmpeg and really dont care about asciidoc and manpages.
