### ISSUE TITLE
Release version 0.4.0

### ISSUE THREAD

**Issue by vtorri** [njh/twolame#89]
hello

will the next release be out soon ? The current release has been out in 2017

thank you

**Comment by vtorri** [comment]
now that windows build has been fixed, maybe a release could be considered now (maybe after appveyor integration to compile on Windows)

**Comment by njh** [comment]
Version 0.4.0 is released at long last:
https://github.com/njh/twolame/releases/tag/0.4.0

Final step is to also upload to SourceForge and update the homepage and documentation.

**Comment by njh** [comment]
Now uploaded to SourceForge:
https://sourceforge.net/projects/twolame/files/twolame/0.4.0/

And linked to from the homepage:
http://www.twolame.org/
